# Generated by Django 5.2 on 2025-04-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="estimated_days",
            field=models.PositiveIntegerField(
                blank=True, help_text="Estimated number of days to resolve", null=True
            ),
        ),
    ]
